// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCZFWzKJESu6D31bHnt9jtYL9KQtv9YuI',
    appId: '1:33269041187:web:6c68252ca82178bf7cc996',
    messagingSenderId: '33269041187',
    projectId: 'gastrogridfirebase',
    authDomain: 'gastrogridfirebase.firebaseapp.com',
    storageBucket: 'gastrogridfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4yzV_GUAKEjta7zq5-WC8a6NQW2jNnFA',
    appId: '1:33269041187:android:050141f7174df32a7cc996',
    messagingSenderId: '33269041187',
    projectId: 'gastrogridfirebase',
    storageBucket: 'gastrogridfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ15NNL6k2dnmZRrOtL9Bc9iXJzgd_hqs',
    appId: '1:33269041187:ios:0978f5260c22464c7cc996',
    messagingSenderId: '33269041187',
    projectId: 'gastrogridfirebase',
    storageBucket: 'gastrogridfirebase.appspot.com',
    iosBundleId: 'com.example.gastrogridApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ15NNL6k2dnmZRrOtL9Bc9iXJzgd_hqs',
    appId: '1:33269041187:ios:13ef1dac9e2b513a7cc996',
    messagingSenderId: '33269041187',
    projectId: 'gastrogridfirebase',
    storageBucket: 'gastrogridfirebase.appspot.com',
    iosBundleId: 'com.example.gastrogridApp.RunnerTests',
  );
}
